/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    string crackSafe(int n, int k) {
        string ans = string(n - 1, '0');
        string res = "";
        int h = pow(10, n - 1);
        unordered_set<int> vis;
        function<void(int)> dfs = [&](int u) {
            for (int i = 0; i < k; i++) {
                int val = (u * 10 + i);
                if (vis.count(val) == 0) {
                    vis.insert(val);
                    dfs(val % h);
                    res.push_back('0' + i);
                }

            }
        };
        dfs(0);
        reverse(res.begin(), res.end());
        ans += res;
        return ans;
    }
};