/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    bool xorGame(vector<int>& nums) {
        int res = 0;
        int n = nums.size();
        if (n % 2 == 0) return true;
        for (int i = 0; i < n; i++) res ^= nums[i];
        if (res == 0) return true;
        return false;
    }
};