"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def firstMissingPositive(self, nums: List[int]) -> int:
        n = len(nums)
        nums.append(0)
        for i in range(n):
            if nums[i] <= 0 or nums[i] > n:
                nums[i] = -1
        for i in range(n):
            if nums[i] == -1:
                continue
            if nums[i] == n + 1:
                continue
            now = nums[i]
            while now >= 1 and now <= n:
                go = nums[now]
                nums[now] = n + 1
                now = go
        now = 1
        while now <= n and nums[now] == n + 1:
            now += 1
        return now
