/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int maxCoins(vector<int>& nums) {
        int n = nums.size();
        nums.insert(nums.begin(), 1);
        nums.push_back(1);
        vector<vector<int>> dp(n + 2, vector<int>(n + 2, 0));
        for (int len = 1; len <= n; len++) {
            for (int i = 1; i + len - 1 <= n; i++) {
                int r = i + len - 1;
                if (len == 1) {
                    dp[i][r] = nums[i] * nums[i - 1] * nums[i + 1];
                } else {
                    for (int k = i; k <= r; k++) {
                        dp[i][r] = max(dp[i][r], dp[i][k - 1] + dp[k + 1][r] + nums[i - 1] * nums[r + 1] * nums[k]);
                    }
                }
                // debug(i, r, dp[i][r]);
            }
        }
        return dp[1][n];
    }
};