"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def mergeKLists(self, lists: List[Optional[ListNode]]) -> Optional[ListNode]:
        if len(lists) == 0:
            return None

        pq = []

        for i in range(len(lists)):
            if lists[i] is not None:
                heapq.heappush(pq, (lists[i].val, i))

        if len(pq) == 0:
            return None
        
        head_idx = heapq.heappop(pq)[1]
        head = lists[head_idx]
        cur = head
        if cur.next is not None:
            heapq.heappush(pq, (cur.next.val, head_idx))
            lists[head_idx] = cur.next
        
        while len(pq) > 0:
            idx = heapq.heappop(pq)[1]
            cur.next = lists[idx]
            cur = cur.next
            if cur.next is not None:
                heapq.heappush(pq, (cur.next.val, idx))
                lists[idx] = cur.next
        
        return head



                
