/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int nthMagicalNumber(int n, int a, int b) {
        int g = __gcd(a, b);
        long long c = 1LL * a * b / g;

        long long l = 1, r = 4e13;
        long long ans = -1;
        while (l <= r) {
            long long mid = l + r >> 1;
            long long num = mid / a + mid / b - mid / c;
            if (num >= n) {
                ans = mid;
                r = mid - 1;
            } else {
                l = mid + 1;
            }
        }
        return ans % (int)(1e9 + 7);
    }
};