/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int findKthNumber(int n, int m, int k) {

        int l = 1, r = n * m;
        int ans = -1;

        auto work = [&](int val) {
            int num = 0;
            for (int i = 1; i <= n; i++) {
                num += min(m, val / i);
            }
            return num;
        };

        while (l <= r) {
            int mid = l + r >> 1;
            int num = work(mid);
            if (num >= k) {
                ans = mid;
                r = mid - 1;
            } else {
                l = mid + 1;
            }
        }
        return ans;


    }
};