/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int findMin(vector<int>& nums) {
        int n = nums.size();
        int l = 0, r = n - 1;
        int ans = -1;
        int res = 1e9;
        while (l <= r) {
            int mid = l + r >> 1;
            if (nums[mid] > nums[l]) {
                res = min(res, nums[l]);
                l = mid + 1;
            } else if (nums[mid] < nums[l]) {
                ans = mid;
                r = mid - 1;
            } else {
                res = min(res, nums[l]);
                l++;
            }
        }
        if (ans == -1) ans = 0;

        res = min(res, nums[ans]);
        return res;

    }
};