/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    bool areSimilar(vector<vector<int>>& mat, int k) {
        int n = mat.size();
        int m = mat[0].size();

        for (int i = 0; i < n; i++) {
            int idx = i + 1;
            int flag;
            if (idx % 2) {
                flag = 1;
            } else {
                flag = -1;
            }

            for (int j = 0; j < m; j++) {
                int j2 = ((j + k * flag) % m + m) % m;
                if (mat[i][j] != mat[i][j2]) return false;
            }
        }
        return true;
    }
};