/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int numberOfArithmeticSlices(vector<int>& nums) {
        int n = nums.size();
        if (n <= 2) return 0;
        unordered_map<int, unordered_map<long long, int>> M;
        M[1][1LL * nums[1] - nums[0]]++;
        int ans = 0;
        for (int i = 2; i < n; i++) {
            for (int j = 0; j < i; j++) {
                long long val = 1LL * nums[i] - nums[j];
                int tmp = M[j][val] + 1;
                if (tmp >= 2) {
                    ans += tmp - 1;
                }
                M[i][val] += tmp;
            }
        }
        return ans;
    }
};