"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def findSubstring(self, s: str, words: List[str]) -> List[int]:
        n = len(words)
        m = len(words[0])

        M = {}
        IDX = {}
        idx = 0
        for word in words:
            if word not in IDX:
                IDX[word] = idx
                idx += 1
            M[IDX[word]] = M.get(IDX[word], 0) + 1

        ans = []
        sz = len(s)
        for i in range(0, m):
            now = M.copy()
            if i + n * m - 1 >= sz:
                break
            for j in range(i, i + n * m, m):
                word = s[j:j+m]
                tmp = IDX[word] if word in IDX else -1
                now[tmp] = now.get(tmp, 0) - 1
                if now[tmp] == 0:
                    del now[tmp]
            now_idx = i
            while now_idx + m * n - 1 < sz:
                if len(now) == 0:
                    ans.append(now_idx)
                if now_idx + m * (n + 1) - 1 >= sz:
                    break
                word = s[now_idx:now_idx+m]
                tmp = IDX[word] if word in IDX else -1
                now[tmp] = now.get(tmp, 0) + 1
                if now[tmp] == 0:
                    del now[tmp]
                word = s[now_idx + m * n:now_idx + m * (n + 1)]
                tmp = IDX[word] if word in IDX else -1
                now[tmp] = now.get(tmp, 0) - 1
                if now[tmp] == 0:
                    del now[tmp]
                now_idx += m
        return ans
                
