/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int maxDistToClosest(vector<int>& seats) {
        int n = seats.size();
        vector<int> V;
        for (int i = 0; i < n; i++) {
            if (seats[i]) {
                V.push_back(i);
            }
        }

        int res = max(V[0], n - 1 - V[V.size() - 1]);

        for (int i = 0; i < V.size() - 1; i++) {
            res = max(res, (V[i + 1] - V[i]) / 2);
        }
        return res;
    }
};