/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int flipgame(vector<int>& fronts, vector<int>& backs) {
        int n = fronts.size();
        set<int> S;
        for (int i = 0; i < n; i++) {
            if (fronts[i] == backs[i]) {
                S.insert(fronts[i]);
            }
        }

        int res = 1e9;
        for (int i = 0; i < n; i++) {
            if (S.count(fronts[i]) == 0) {
                res = min(res, fronts[i]);
            }
            if (S.count(backs[i]) == 0) {
                res = min(res, backs[i]);
            }
        }
        if (res == 1e9) res = 0;
        return res;
    }
};