/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
public:
    long long minimumPossibleSum(int n, int target) {
        if (n == 1) {
            return 1;
        }
        
        set<int> S;
        long long ans = 0;
        int now = 1;
        for (int i = 0; i < n; i++) {
            int other = target - now;
            while (S.count(other)) {
                now++;
                other = target - now;
            }
            ans += now;
            S.insert(now);
            now++;
        }
        return ans;
        
        
        
    }
};