/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int maxPoints(vector<vector<int>>& points) {
        int n = points.size();
        if (n == 1) return 1;
        int ans = 0;
        auto check = [&](int i, int j, int k) {
            return (points[i][1] - points[j][1]) * (points[i][0] - points[k][0]) == (points[i][0] - points[j][0]) * (points[i][1] - points[k][1]);
        };
        for (int i = 0; i < n; i++) {
            for (int j = i + 1; j < n; j++) {
                int cnt = 2;
                for (int k = j + 1; k < n; k++) {
                    if (check(i, j, k)) cnt++;
                }
                ans = max(ans, cnt);
            }
        }
        return ans;


    }
};