/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

typedef pair<int, int> pii;
class Solution {
   public:
    int trap(vector<int>& height) {
        int n = height.size();
        vector<pii> V(n);
        for (int i = 0; i < n; i++) {
            V[i] = {height[i], i};
        }
        sort(V.rbegin(), V.rend());
        int ans = 0;

        set<int> S;

        for (int i = 0; i < n; i++) {
            auto it = V[i];

            int h = it.first, idx = it.second;
            if (S.size() == 0) {
                S.insert(idx);
            } else {
                auto it2 = S.lower_bound(idx);
                if (it2 == S.end()) {
                    it2--;
                    int idx2 = *it2;
                    ans += (idx - idx2 - 1) * h;
                } else if (it2 == S.begin()) {
                    int idx2 = *it2;
                    ans += (idx2 - idx - 1) * h;
                } else {
                    ans -= h;
                }
                S.insert(idx);
            }
        }
        return ans;
    }
};