"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def uniquePathsIII(self, grid: List[List[int]]) -> int:
        n = len(grid)
        m = len(grid[0])
        start = None
        end = None
        for i in range(n):
            for j in range(m):
                if grid[i][j] == 1:
                    start = (i, j)
                elif grid[i][j] == 2:
                    end = (i, j)
        
        N = n * m
        LIMIT = 1 << (N)
        dis = [[0] * LIMIT for _ in range(N)] # N * LIMIT
        vis = [[False] * LIMIT for _ in range(N)] # N * LIMIT
        q = deque()

        def get_state(x, y):
            return x * m + y
        
        def get_pos(state):
            return (state // m, state % m)
        
        start_state = get_state(*start)
        dis[start_state][1 << start_state] = 1

        d = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        q.append((start_state, 1 << start_state))

        while q:
            cur = q.popleft()
            location = get_pos(cur[0])
            if vis[cur[0]][cur[1]]:
                continue
            vis[cur[0]][cur[1]] = True
            for dx, dy in d:
                x2 = location[0] + dx
                y2 = location[1] + dy
                if x2 < 0 or x2 >= n or y2 < 0 or y2 >= m:
                    continue
                if grid[x2][y2] == -1:
                    continue
                state = get_state(x2, y2)
                if cur[1] & (1 << state):
                    continue
                dis[state][cur[1] | (1 << state)] += dis[cur[0]][cur[1]]
                q.append((state, cur[1] | (1 << state)))
        
        status = 0
        for i in range(n):
            for j in range(m):
                if grid[i][j] != -1:
                    status |= (1 << (get_state(i, j)))
        
        # print(status)
        return dis[get_state(*end)][status]
                
