/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    vector<int> maxSlidingWindow(vector<int>& nums, int k) {
        int r = 0;
        int n = nums.size();
        multiset<int> S;
        vector<int> ans;
        for (int i = 0; i + k - 1 < n; i++) {
            while (r - i + 1 <= k) {
                S.insert(nums[r++]);
            }
            ans.push_back(*S.rbegin());
            S.erase(S.find(nums[i]));
        }
        return ans;
    }
};