/*
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
*/
#if __has_include("../utils/cpp/help.hpp")
#include "../utils/cpp/help.hpp"
#elif __has_include("../../utils/cpp/help.hpp")
#include "../../utils/cpp/help.hpp"
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int findMinMoves(vector<int>& machines) {
        int n = machines.size();
        int sum = accumulate(machines.begin(), machines.end(), 0);
        if (sum % n) return -1;
        int val = sum / n;
        int ans = 0;
        sum = 0;
        for (int i = 0; i < n; i++) {
            int tmp = machines[i] - val;
            sum += tmp;
            ans = max(ans, max(abs(sum), tmp));
        }
        return ans;
    }
};